name: CI Pipeline

on:
  push:
    branches: [ main ]

jobs:
  python-scripts:
    name: Run Python Scripts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install boto3
        run: pip install boto3

      - name: Run CSVAnalysis.py
        run: python CSVAnalysis.py

      - name: Run NoOfObjectsInS3.py
        run: python NoOfObjectsInS3.py

  terraform:
    name: Validate Terraform
    needs: python-scripts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform init
        run: terraform init

      - name: Terraform validate
        run: terraform validate

      - name: Terraform plan
        run: terraform plan
